/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ventana;

import Control.ControlGeneraMov;
import javax.swing.JOptionPane;

/**
 *
 * @author Pepe
 */
public class GeneraMov extends javax.swing.JFrame {
    private final ControlGeneraMov control;
    /**
     * Creates new form Traspasos
     */
    public GeneraMov() {
        initComponents();
        control = new ControlGeneraMov(this);
        buttonGroup1.add(rbEntrada);
        buttonGroup1.add(rbSalida);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        tfArticulo = new javax.swing.JTextField();
        btCrear = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        tfAlmacen = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tfUnidades = new javax.swing.JTextField();
        rbEntrada = new javax.swing.JRadioButton();
        rbSalida = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Traspasos Manuales");

        jLabel1.setText("Artículo");

        tfArticulo.setToolTipText("Artículo");

        btCrear.setText("Buscar");
        btCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCrearActionPerformed(evt);
            }
        });

        jLabel2.setText("Almacén");
        jLabel2.setToolTipText("");

        tfAlmacen.setToolTipText("Artículo");

        jLabel4.setText("Unidades");

        tfUnidades.setToolTipText("Artículo");

        rbEntrada.setText("Entrada");

        rbSalida.setText("Salida");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(tfUnidades, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfAlmacen, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(tfArticulo, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rbEntrada))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbSalida)
                    .addComponent(btCrear))
                .addGap(118, 118, 118))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbSalida)
                    .addComponent(rbEntrada))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfAlmacen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfArticulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfUnidades, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btCrear))
                .addGap(23, 23, 23))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCrearActionPerformed
        if (tfAlmacen.getText().equals("") || tfArticulo.getText().equals("") || 
                tfUnidades.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Debe rellenar todos los campos",
                    "Error", JOptionPane.ERROR_MESSAGE); 
        } else {
            try {
                String tipo;
                if (rbEntrada.isSelected()) {
                    tipo = "E";
                } else {
                    tipo = "S";
                }
                control.crearMovimiento(tipo, tfAlmacen.getText(),tfArticulo.getText(),
                        Integer.parseInt(tfUnidades.getText()));
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Las unidades deben de ser un número",
                        "Error", JOptionPane.ERROR_MESSAGE); 
            }
        }
    }//GEN-LAST:event_btCrearActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCrear;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JRadioButton rbEntrada;
    private javax.swing.JRadioButton rbSalida;
    public javax.swing.JTextField tfAlmacen;
    public javax.swing.JTextField tfArticulo;
    public javax.swing.JTextField tfUnidades;
    // End of variables declaration//GEN-END:variables
}
