/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ventana;

import Control.ControlMenu;

/**
 *
 * @author Pepe
 */
public class MenuPrincipal extends javax.swing.JFrame {

    private static ControlMenu control;
    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
        control = new ControlMenu(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnTitulo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        pnBotones = new javax.swing.JPanel();
        btTraspaso = new javax.swing.JButton();
        btVerStock = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("App Gestión Almacén");
        setName(""); // NOI18N
        setPreferredSize(new java.awt.Dimension(1000, 500));

        pnTitulo.setMinimumSize(new java.awt.Dimension(500, 0));
        pnTitulo.setPreferredSize(new java.awt.Dimension(0, 50));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("GESTIÓN ALMACÉN");

        javax.swing.GroupLayout pnTituloLayout = new javax.swing.GroupLayout(pnTitulo);
        pnTitulo.setLayout(pnTituloLayout);
        pnTituloLayout.setHorizontalGroup(
            pnTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnTituloLayout.createSequentialGroup()
                .addContainerGap(83, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 324, Short.MAX_VALUE)
                .addContainerGap(93, Short.MAX_VALUE))
        );
        pnTituloLayout.setVerticalGroup(
            pnTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jLabel1.getAccessibleContext().setAccessibleDescription("");

        getContentPane().add(pnTitulo, java.awt.BorderLayout.NORTH);

        pnBotones.setToolTipText("");
        pnBotones.setPreferredSize(new java.awt.Dimension(500, 500));

        btTraspaso.setText("Traspaso Manual");
        btTraspaso.setMargin(new java.awt.Insets(2, 50, 2, 50));
        btTraspaso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTraspasoActionPerformed(evt);
            }
        });

        btVerStock.setText("Ver Stock");
        btVerStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVerStockActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnBotonesLayout = new javax.swing.GroupLayout(pnBotones);
        pnBotones.setLayout(pnBotonesLayout);
        pnBotonesLayout.setHorizontalGroup(
            pnBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnBotonesLayout.createSequentialGroup()
                .addGap(0, 153, Short.MAX_VALUE)
                .addGroup(pnBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btTraspaso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btVerStock, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(162, Short.MAX_VALUE))
        );
        pnBotonesLayout.setVerticalGroup(
            pnBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnBotonesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btTraspaso)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btVerStock)
                .addContainerGap())
        );

        getContentPane().add(pnBotones, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btTraspasoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTraspasoActionPerformed
       // new RecepcionAlmacen().setVisible(true);
       new Traspasos().setVisible(true);
    }//GEN-LAST:event_btTraspasoActionPerformed

    private void btVerStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVerStockActionPerformed
        new VerStock().setVisible(true);
    }//GEN-LAST:event_btVerStockActionPerformed

    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btTraspaso;
    private javax.swing.JButton btVerStock;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel pnBotones;
    private javax.swing.JPanel pnTitulo;
    // End of variables declaration//GEN-END:variables
}
